name: Build and Publish Go Binary

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum
    
    - name: vet
      run: go vet ./...

    - name: Build
      env:
        GOOS: linux
        GOARCH: arm
      run: go build -o ./build/fan-light-check .

    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: ./build/fan-light-check

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: download artifacts
        uses: actions/download-artifact@v4
        with:
          name: binary
          path: ./build/fan-light-check
      
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          git-user-name: github-actions
          git-user-email: actions@github.com
          fallback-version: 0.0.0
          skip-commit: true
          git-push: false

      - name: Commit release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "chore(release): ${{ steps.changelog.outputs.tag }} [skip ci]"

      - name: Push changes
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        run: |
          git push origin main --follow-tags

      - name: Create Release
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          name: ${{ steps.changelog.outputs.tag }}
          tag: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          token: ${{ github.token }}
          artifacts: ./build/fan-light-check
